# Generated by Django 3.1.5 on 2021-01-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
    ]
